### ISSUE TITLE
Perl dependancies are missing.

### ISSUE THREAD

**Issue by happykhan** [phac-nml/irida#231]
I've used the irida auto tool installer to configure my galaxy with all the irida pipelines. 
I've found a missing perl dependencies. The installer says everything is installed fine; so it would be good if it either 

1. installed the perl libraries
2. warned me that I need to install these libraries.

So far it is:

- autodie and Parallel::ForkManager, & ReadOnly  for the snvlyphml pipeline
- & Bioperl for the assembly/annotation pipeline.

**Comment by apetkau** [comment]
Thanks for reporting. Some of these missing dependencies should be fixed in our upcoming release where we've switched to all bioconda dependencies for the assembly/annotation pipeline (so it should install all dependencies automatically).

For the SNVPhyl pipeline, I do try and list some dependencies that don't get installed automatically at https://irida.corefacility.ca/documentation/administrator/galaxy/pipelines/phylogenomics/ (eventually I want to wrap all these up into a snvphyl conda package, but hasn't been quite completed yet).  I do agree it would be much more convenient if the installer warned you about some of these missing dependencies.
