### ISSUE TITLE
Create documentation for irida-galaxy-importer

### ISSUE THREAD

**Issue by joshsadam** [phac-nml/irida#276]
## Describe your idea for a new feature
Write out the steps required to set up the importer tool.

**Comment by apetkau** [comment]
Make sure documentation mentions that the **access** field must be left blank in Galaxy in **User > Preferences > Set data permissions for new histories**

![image](https://user-images.githubusercontent.com/200517/55976801-ed4f9480-5c52-11e9-8899-de8fceb55f49.png)

Otherwise, users may wind up with the dataset files in the **Data Library** inaccessible for all but the user configured to communicate with the Galaxy API in the importer tool:

![image](https://user-images.githubusercontent.com/200517/55976872-14a66180-5c53-11e9-94d7-8e5a67a63bee.png)

**Comment by apetkau** [comment]
Fixed in #447
