### ISSUE TITLE
NCBI SRA link is broken in docs

### ISSUE THREAD

**Issue by tom114** [phac-nml/irida#348]
## Describe the bug
Link to NCBI docs to set up bulk SRA uploader is broken.  Previously linked to https://www.ncbi.nlm.nih.gov/books/NBK47529/#_SRA_Quick_Sub_BK_Establishing_a_Center_A_

> NCBI SRA export configuration - An SRA bulk upload user account must be created with NCBI to allow automated SRA uploads. See *NCBI SRA Handbook* for details.

## Steps to reproduce the problem
What were you doing when you encountered the problem?
1. Go to https://irida.corefacility.ca/documentation/administrator/web/ page
2. Click on NCBI SRA Handbook link
3. 404

## Expected behaviour
What did you expect to happen?
Go to a page describing bulk upload

## Additional context
@tom114 has done some looking into their current docs and I don't see where this section is now located.  This bit of docs might need to be revised.

**Comment by tom114** [comment]
Closest I can find to the docs is https://www.ncbi.nlm.nih.gov/biosample/docs/submission/faq/ which links to https://www.ncbi.nlm.nih.gov/viewvc/v1/trunk/submit/public-docs/, but all the docs folders are empty in there.

**Comment by tom114** [comment]
We should as part of this update the docs on how the NCBI uploader works.

**Comment by apetkau** [comment]
I asked NCBI what happened to these books and was informed that they were out-of-date and were removed. I cannot find any more documentation about this. I believe the expected method to setup such an account is to email NCBI (the SRA support email) directly and ask for a "Center account for simplified format" and that you want to use the FTP (instead of Aspera) method to connect.
