### ISSUE TITLE
Issues with creating new workflow/pipeline in IRIDA

### ISSUE THREAD

**Issue by rat-codes** [phac-nml/irida#5]
Hi,

I have installed IRIDA and GALAXY on my server, and was able to run SNVPhyl pipeline successfully. I want to add a new pipeline in IRIDA and have followed through all the steps outlined in [this](https://irida.corefacility.ca/documentation/developer/tools/pipelines/) documentation. Although, I can see the new pipeline in the UI, I am unable to submit it (no launch button is displayed) and see a "{{pipeline.error}}" just below the submission name. 

The new pipeline has only two tools 'smalt-index' and 'smalt-map' (which are also found in SNVPhyl)

By grepping the name of default pipelines, 

1. I find that more class files needs to edited apart from the AnalysisType.java & AnalysisMypipeline.java as advised in the documentation.
    Example: src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/RESTAnalysisSubmissionController.java
2. Does the following files too require to be edited?
- src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/3.6.0/all-changes.sql
- src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/3.0.0/replace-analysis-workflows.xml
- src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/2.0/analysis-output-file.xml

Appreciate your help on this. Please advise if it is possible to add a new pipeline. 

PS: I am currently using 0.16.0 dev branch. 

Thanks & regards,
Aarthi

**Comment by apetkau** [comment]
Hello Aarthi,

Are there any error messages in the IRIDA log files around the time you see the `{{pipeline.error}}` message?

To answer your questions:

1. There are a few more files where the default pipelines show up, but you shouldn't need to modify any of these to get everything to work.  For example, the file `src/main/java/ca/corefacility/bioinformatics/irida/web/controller/api/RESTAnalysisSubmissionController.java` is used to make available the pipeline results via our REST API.  This is unnecessary if you are only interested in interacting with IRIDA via the user interface.

2. The other few files you listed do not need to be edited either:
   * `all-changes.sql`: These are cached copies of particular versions of our database.  They do not need to be modified.
   * `changes/*/*.xml`: These define how to construct the database for different versions of IRIDA (using [liquibase](http://www.liquibase.org/)).

However, there are a few additional modifications you will have to make that are not listed.  In particular:

1. You will have to add a liquibase XML file under `changesets/` to match the newly added [analysis type](https://irida.corefacility.ca/documentation/developer/tools/pipelines/#pipeline-data-model). As an example, see below:

    1. Create a new directory like `src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/0.16.0-mypipeline/` and add a new file here `all-changes.xml`.  This file will look as follows (change `mypipeline` with your database table name):

        ```xml
        <?xml version="1.0" encoding="UTF-8"?>
        
        <databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
        	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        	xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
                 http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.1.xsd">
        
        	<changeSet id="mypipeline" author="aaron">
        		<createTable tableName="analysis_mypipeline">
        			<column name="id" type="bigint(20)">
        				<constraints primaryKey="true" nullable="false"
        					referencedTableName="analysis" referencedColumnNames="id"
        					foreignKeyName="FK_ANALYSIS_MYPIPELINE_ANALYSIS" />
        			</column>
        		</createTable>
        	</changeSet>
        </databaseChangeLog>
        ```

    As an other example, you can see [this file](https://github.com/phac-nml/irida/blob/development/src/main/resources/ca/corefacility/bioinformatics/irida/database/changesets/3.0.0/analysis-assembly-annotation.xml).

    2. Modify the file `src/main/resources/ca/corefacility/bioinformatics/irida/database/all-changes.xml` and add the line (to point to your new database changes):

        ```xml
        <include file="changesets/0.16.0-mypipeline/all-changes.xml" relativeToChangelogFile="true"/>
        ```

This should be all you need to do that's missing from the documentation currently.  Also, since this change is modifying the database schema (when you first start IRIDA), if you have important data in the database please make sure to back it up beforehand.

I'm sorry some of our documentation is incomplete and that there's so many files to change to get a pipeline integrated.  We eventually want to simplify this process.  Please let me know if you have any more issues,

Aaron

**Comment by rat-codes** [comment]
![pipelines_display](https://cloud.githubusercontent.com/assets/8120708/24988434/7b2f46a0-2038-11e7-8dd0-26a2ecf4ead8.png)
[localhost_logs.txt](https://github.com/phac-nml/irida/files/918408/localhost_logs.txt)

Hi Aaron,

Thanks for your detailed response. I have tried using the stable version 0.15.1 and made changes as suggested here along with the original documentation. But, I still see the same errors. I am attaching a screenshot of the UI and also the logs from tomcat. 

Also I found that the 

1. AnalysisMyPipleine.java file in the following path should include some 'import' statements similar to the default pipeline class files. 
> src/main/java/ca/corefacility/bioinformatics/irida/model/workflow/analysis/AnalysisMyPipeline.java
 
2. AnalysisType.java  file in the following path needs an import statement for the new pipeline. 
> src/main/java/ca/corefacility/bioinformatics/irida/model/enums/AnalysisType.java

In Galaxy, when I create the workflow, I leave all parameters default and hence to match it I thought I shouldn't be passing any parameters here either. So, I have not added anything related to parameters in the '_message_en_properties_' file. Please let me know if this could contribute to the problem. 

I will be glad to send any other required files to identify the problem. 

Thanks for your help!

Best,
Aarthi
[catalina.out.txt](https://github.com/phac-nml/irida/files/918407/catalina.out.txt)
![pipeline_error_onsubmission](https://cloud.githubusercontent.com/assets/8120708/24988429/74cefc60-2038-11e7-8f89-9ac4622c6428.png)

**Comment by joshsadam** [comment]
Hi Aarthi,

 Aaron really is the expert at this stuff, but I wrote most of the client side code for it. The `{{pipeline.error}}` is an angularjs expression for templating.  The fact that you are seeing that itself on the web page tells me that you are having some javascript errors, and angularjs is not interpolating properly.  Can you open up the development tools when you are on that pipeline launch page and post here any error messages that are appearing in the console?

Thanks
Josh

**Comment by rat-codes** [comment]
Hi Josh,

Thanks for your help. The message from console. Please let me know if this wasn't what you asked for!

```
TypeError: Cannot read property 'map' of null
    at new ParameterService (launch-pipeline-55103cb….js:20)
    at Object.instantiate (angular.js:4619)
    at Object.<anonymous> (angular.js:4459)
    at Object.invoke (angular.js:4604)
    at Object.enforcedReturnValue [as $get] (angular.js:4443)
    at Object.invoke (angular.js:4604)
    at angular.js:4403
    at getService (angular.js:4550)
    at injectionArgs (angular.js:4574)
    at Object.invoke (angular.js:4596)
(anonymous) @ angular.js:13236
```

Best,
Aarthi

**Comment by joshsadam** [comment]
Ok, so now I think I know what is going on - and is completely my fault that it is occurring. The pipeline launch page is expecting parameters for the pipeline, since you are not passing any, it fails when it tries to iterate over them - I forget to check for this and since all our pipelines currently use parameters we have not run into this issue.

**What is actually happening:**
The parameters are added to the launch page starting at line 310 of `PipelineController.java`.  Since your parameters are empty the `parameters` array is not passed to the page `model` which in turn results in the variable `PAGE.pipline.parameters` being set to `null` on line 22 of `generic_pipeline.html`. With this set to `null`,  line 326 of `pipeline.launch.js` tries to iterate over the pipeline parameters and fails throwing this error.

### Temporary Hack:
Part of how I am going to fix this is to move line 337 of `PipelineController.java` outside of the enclosing if statement to somewhere around line 343.  This will set that `Page.pipeline.parameters` variable to an empty array in your can which will allow the javascript to execute properly.

_**DONT'T COMMIT THIS CODE.**  Only do this until either you have pipeline parameters you want to use, or I can push out a check to see if the pipeline parameters are actually there._

Please let me now if this temporary solution works, and if you have any more issues (or comments about ways to make the user interface better).

Josh

**Comment by rat-codes** [comment]
Hi Josh,

The "{{error.pipeline}}"  disappears after moving  `model.addAttribute("parameters", parameters);` from line 337 to 343 in PipelineController.java. And also displays the 'Ready to Launch' button, However, the actual submission does not happen. '**Your analyses**' list is empty and I don't see any submission happening from catalina.out or galaxy end as well. 

Please let me know if you would need any files from my side. The site looks great, and will be happy to share our feed backs once we start using it more. 

Thank you for helping me. I really appreciate it!

Best,
Aarthi

**Comment by rat-codes** [comment]
Hi Aaron and Josh,

Just two general question regarding the communication b/w IRIDA and GALAXY. 

1.  Does IRIDA pass it's data directory (directory where it stores the fastq, reference files) to GALAXY directly? Because when we set them up in two different servers, IRIDA failed at submit step. But, upon setting it to a general path available in both servers like (/data or /opt), and make one server point to other (mounting), then IRIDA is able to submit the analysis successfully. 

2. I found that every time I run the SNVPhyl pipeline, IRIDA is uploading a copy of the workflow.ga file to GALAXY. So, there are so many copies of the same pipeline in GALAXY.

Thanks,
Aarthi

**Comment by joshsadam** [comment]
I will leave your galaxy question to @apetkau as I do not work in that area. As for your previous question, try putting a break point in at line 527 of `PipelineController.java` and see if it reaches that point when you try launching your pipeline.  Inspect the `results` variable and let me know what you see in it.  You hopefully will not see any `pipelineError` messages.

**Comment by apetkau** [comment]
1. Yes, IRIDA passes it's data directory to Galaxy.  The files need to be accessible under the same path on both the IRIDA server and the Galaxy server.

2. Yes, IRIDA uploads a copy of the workflow.ga file every time a pipeline is run. There is a parameter in IRIDA `irida.analysis.cleanup.days` as well as some additional steps in Galaxy you can take to periodically clean up intermediate and temporary files produced by each analysis pipeline (which includes the multiple copies of the uploaded workflows in Galaxy). See https://irida.corefacility.ca/documentation/administrator/galaxy/#configure-galaxy-data-cleanup

**Comment by rat-codes** [comment]
Hi Josh and Aaron, thanks for your help. I have modified the workflow to accept one parameter at least. I will close this issue. Thanks again for the help!
