### ISSUE TITLE
Could not determine version of minced - please install version 1.6 or higher

### ISSUE THREAD

**Issue by glwinsor** [phac-nml/irida#50]
I'm getting this error while running prokka in our workflows on our dev Galaxy instance even though it should be a mirror of our production instance (which is running prokka OK) .

<img width="776" alt="screen shot 2018-07-01 at 2 08 39 pm" src="https://user-images.githubusercontent.com/824607/42138877-9fdc3620-7d39-11e8-96e3-1d2cba9223dd.png">

By doing a Google search, it appears the standalone 1.6 toolshed version of minced is compiled using Java 8 while the version included with prokka is compiled using Java 6. 

https://github.com/tseemann/prokka/issues/162

I tried deleting the standalone copy so that it would use the dependency included with prokka but I get the same error.

Both production and dev Galaxy instances are using the same version of prokka (1.11, revision f5e44aad649, crs4) and version 1.6 of minced (revision a135862cd007, takadonet).

Any ideas on how to troubleshoot this one?

**Comment by apetkau** [comment]
It looks like the root cause of this issue is from the line `java: command not found`.  That is, `java` is not found in the `PATH` when running prokka.  I believe prokka runs `minced` (and other tools) first to check for the version, so if java is not available prokka can't check the version and so reports an error.

One solution for this problem is to make sure Java is installed on your Galaxy server and all cluster notes.  Another solution is to install Java using `conda`, and then load up the conda environment before running each tool.  This can be accomplished by setting `environment_setup_file = /path/to/env.sh` in the [galaxy.ini](https://github.com/galaxyproject/galaxy/blob/release_17.09/config/galaxy.ini.sample#L1355) config file and then in the `/path/to/env.sh` file loading up the conda environment with Java.  For example:

1. Install java in a `conda` environment:

```bash
conda create --name galaxy openjdk
```

2. Configure `env.sh` to load conda environment
```
export PATH=/path/to/miniconda3/bin:$PATH
source activate galaxy
```

The file `env.sh` will get sourced before execution of every tool, which means that ever tool will now have `java` in the `PATH`.

Some additional documentation on this is in https://irida.corefacility.ca/documentation/administrator/galaxy/existing-galaxy/#dependencies

I hope this helps you out.

**Comment by glwinsor** [comment]
Thanks, 
This makes sense to me. The error is only occurring in the test environment (not the production environment running same Galaxy and IRIDA release), suggesting that the instance configurations aren't perfectly synced. I'll have to run it by our guy in research computing.
