### ISSUE TITLE
tbl2asn/Prokka self-destructs after a certain date

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#58]
Hey,

So, Phil warned me about this a while ago, but I hadn't tried to address it.  We're using Prokka for annotations, which uses `tbl2asn` from NCBI.  `tbl2asn` self-destructs after a year and refuses to run.

Phil had been addressing this by manually re-downloading and swapping out the binary on Galaxy.  However, this messes up with reproducibility since we either don't keep track of the exact version of tbl2asn (swap it out on our own and not update the Galaxy tool), or we update our workflow for annotation every year and just leave old versions unable to complete.

I was reminded of this now because we've hit that point:

```
Fatal error: Exit code 2 ()
[tbl2asn] This copy of tbl2asn is more than a year old.  Please download the current version.
[16:53:38] Could not run command: tbl2asn -V b -a r10k -l paired-ends -M n -N 1 -y 'Annotated using prokka 1.10 from http://www.vicbioinformatics.com' -Z outdir\/prokka\.err -i outdir\/prokka\.fsa 2> /dev/null
```

Thoughts @franklin.bristow and @thomas.matthews .  Not sure the best way to address this, but from now on all assemblies/annotations in IRIDA will fail.

Imported from GitLab issue #315.  Originally posted on 2015/09/04 11:07AM

**Comment by tom114** [comment]
I know.  I remember asking Torsten about that, I can't recall if he make it an optional output – the gbk file was meant to pave the way for submitting a sequence there, or project as I recall.  (It would be nice if that was going to be superseded by IRIDA's other NCBI submission metadata anyways).

D.

Imported from GitLab.  Originally posted on 2017/03/06 06:52PM
Originally posted by Damion Dooley

**Comment by apetkau** [comment]
I just replace both, though IRIDA is using the one in takadonet/pacakge_tbl2asn_24_3.

Thanks for asking at NCBI.  It is a pain.  It's only really used to generate a gbk file within prokka though.  I have wondered how often people use that/if it would make sense to just skip over generating it (and so skip over using tbl2asn).

Imported from GitLab.  Originally posted on 2017/03/06 06:37PM

**Comment by tom114** [comment]
In my install I see these locations:

./tool_dependencies/tbl2asn/24.3/takadonet/package_tbl2asn_24_3/41764d6a6a3c/bin/tbl2asn
./tool_dependencies/tbl2asn/24.3/takadonet/package_tbl2asn_24_3/41764d6a6a3c/bin/tbl2asn-expired
./tool_dependencies/prokka/1.11/crs4/prokka/f5e44aad6498/binaries/darwin/tbl2asn
./tool_dependencies/prokka/1.11/crs4/prokka/f5e44aad6498/binaries/linux/tbl2asn

Seems like I need to replace the takadonet one.  The prokka linux one is also expired. Which one is IRIDA using?

Imported from GitLab.  Originally posted on 2017/03/06 06:11PM
Originally posted by Damion Dooley

**Comment by tom114** [comment]
hey folks, well, its that time of year!  The day tbl2asn bites one in the butt (just now, on sabin's IRIDA).  I did contact NCBI last year and let them know that I thought this was a design error on their part.  They said their motivation was to ensure clients were keeping up-to-date with any changes to the asn standard.  But I told them that this sinks reproducibility etc. in pipelines.  They were going to think about it but I assume nothing has changed since then.

In meantime do you have instructions on how to swap it out on command line in galaxy?

Imported from GitLab.  Originally posted on 2017/03/06 05:31PM
Originally posted by Damion Dooley

**Comment by apetkau** [comment]
Yeah, I know.  I can add a bit of documentation about when it will expire.  I'm wondering if we can also get someone (our co-op student?) to look into re-building it without the expiry date.  Or, could ask NCBI about that, though I have no idea who I'd contact.

Imported from GitLab.  Originally posted on 2015/11/18 08:22AM

**Comment by tom114** [comment]
This is still something that's going to bite us in a year's time (or at least a year's time since the current `tbl2asn` in Prokka was compiled).

If nothing else, can you document the issue in our documentation?

Imported from GitLab.  Originally posted on 2015/11/18 08:18AM
Originally posted by Franklin Bristow

**Comment by apetkau** [comment]
That could work, and may be one solution.  I nearly have a fix for this though.  Prokka on Galaxy has been updated so I just have to update our workflows.  I'm mostly done with this, just have to test it.  This will solve the issue, for the next year at least.

Imported from GitLab.  Originally posted on 2015/11/18 08:03AM

**Comment by tom114** [comment]
For the VM, I wonder if we should just have a cron job that periodically runs a script that checks to see if `tbl2asn` is expired, and then just download and replace all three versions of it in our tools directories?

That would solve the problem temporarily for the VMs...

Imported from GitLab.  Originally posted on 2015/11/18 07:55AM
Originally posted by Franklin Bristow

**Comment by apetkau** [comment]
Temporarily fixed by swapping `tbl2asn` binary on cluster with one from https://github.com/tseemann/prokka/blob/b57be694218459cd22a06ccacbf62dea5b4b965f/binaries/linux/tbl2asn.  More permanent solution may be to fork/build our own version of tbl2asn from http://www.ncbi.nlm.nih.gov/IEB/ToolBox/C_DOC/lxr/source/demo/tbl2asn.c

Imported from GitLab.  Originally posted on 2015/09/08 02:50PM

**Comment by apetkau** [comment]
I did not know that such scanning existed.  Cool, but yeah, seems like an issue for everyone.

Imported from GitLab.  Originally posted on 2015/09/08 10:55AM

**Comment by tom114** [comment]
The packages that `tbl2asn` comes from have been identified in the Debian reproducible builds automated scanner as being an issue: https://reproducible.debian.net/rb-pkg/testing/amd64/ncbi-tools6.html

Imported from GitLab.  Originally posted on 2015/09/08 10:51AM
Originally posted by Franklin Bristow

**Comment by apetkau** [comment]
I agree.  For an alternative to what `tbl2asn` does, I'm not sure.  Yes, we do expose the outputs of `tbl2asn`.  Mainly, it's used to generate a GenBank file with all the annotations.  I'm not sure currently how many people use that file though.  If we wanted to remove the dependency, we'd have to fork Prokka and maintain our own version which does not generate genbank files.

Imported from GitLab.  Originally posted on 2015/09/08 09:21AM

**Comment by tom114** [comment]
`libfaketime` is not a good scalable plan, anyway (as cool of an idea as it is) because it's another dependency that needs to be installed cluster-wide in a cluster environment.

Is there an alternative tool that does what `tbl2asn` does for what prokka uses it for? Do we currently expose the outputs of `tbl2asn`? If not, do we plan on it? Can we just remove that step from prokka?

Imported from GitLab.  Originally posted on 2015/09/08 08:00AM
Originally posted by Franklin Bristow

**Comment by apetkau** [comment]
So, testing this out, neither using a wrapper script to change the exit code, or 1libfaketime` works.  `tbl2asn` still runs, but no output files are produced.  They are produced when using the newer binary.

Imported from GitLab.  Originally posted on 2015/09/04 04:26PM

**Comment by tom114** [comment]
> For Galaxy, @philip.mabon is the maintainer of tbl2asn https://toolshed.g2.bx.psu.edu/repos/takadonet/package_tbl2asn_23_7/file/2271d52a8531/tool_dependencies.xml. This downloads it from a repository maintained by Björn, part of the Galaxy team, because it looks like ncbi doesn't maintain older versions of tbl2asn (https://github.com/bgruening/download_store/tree/master/ncbi_tools/tbl2asn/23.7/linux64).

takadonet might be a maintainer for *a* version of tbl2asn, but the galaxy wrapped version of prokka that we're using comes from orione, and embeds whatever version of tbl2asn prokka has. Wouldn't the binary version in a git repository have the same problem that we're currently running into?

> (As a side note, it's a cool repository of many bioinformatics binaries, which we may be able to submit things like smalt too and remove our dependency on sourceforge downloads once and for all).

Sure. I mean, I guess we could even have our own git repository that has binaries for all the tools that we want to use, but does this guy have a tool for Galaxy to maintain tools (i.e., we don't have to support our own?)

> Looks like Torsten Seemann maintains tbl2asn binaries too, https://github.com/tseemann/prokka/tree/master/binaries/linux, and just updates in the repo every so often. Maybe he would be open to accepting some sort of wrapper?

Someone has reported this issue to Torsten before (here: https://github.com/tseemann/prokka/issues/96) and his solution was to just update the binary in the git repository. Maybe he would be open to having a wrapper, it's not going to hurt to ask.

I *guess* I understand why NCBI is doing that, to cut down on headaches of people submitting things to NCBI repositories, but jeez, I'd rather them reject something and explain that you should run a newer version of tbl2asn rather than **break** their stupid tool.

Imported from GitLab.  Originally posted on 2015/09/04 03:11PM
Originally posted by Franklin Bristow

**Comment by apetkau** [comment]
Yes, I agree.

For Galaxy, @philip.mabon is the maintainer of tbl2asn https://toolshed.g2.bx.psu.edu/repos/takadonet/package_tbl2asn_23_7/file/2271d52a8531/tool_dependencies.xml.  This downloads it from a repository maintained by Björn, part of the Galaxy team, because it looks like ncbi doesn't maintain older versions of tbl2asn (https://github.com/bgruening/download_store/tree/master/ncbi_tools/tbl2asn/23.7/linux64).  (As a side note, it's a cool repository of many bioinformatics binaries, which we may be able to submit things like `smalt` too and remove our dependency on sourceforge downloads once and for all).

Looks like Torsten Seemann maintains tbl2asn binaries too, https://github.com/tseemann/prokka/tree/master/binaries/linux, and just updates in the repo every so often.  Maybe he would be open to accepting some sort of wrapper?

Imported from GitLab.  Originally posted on 2015/09/04 02:29PM
