### ISSUE TITLE
Allow pipeline plugins to use advanved phylogenetic visualization

### ISSUE THREAD

**Issue by dfornika** [phac-nml/irida#591]
## Describe your idea for a new feature
What is the feature you would like to see in IRIDA?

Allow a way for pipeline plugins to use the advanced phylogenetic visualization system.

## Describe how you would access this feature?
Where would you interact with this feature?  (New pipeline, new button on the project page, REST API, etc.)

Pipeline plugin developers would have a way to configure their plugins to take advantage of the advanced visualization system.

Users would see the advanced visualization system on the Analysis Results page for specific pipeline plugins.

## Additional information
Add any other context, files, or screenshots about the feature request here.

Logic for displaying advanced visualization handled here:

https://github.com/phac-nml/irida/blob/development/src/main/java/ca/corefacility/bioinformatics/irida/ria/web/analysis/AnalysisController.java

**Comment by kbessonov1984** [comment]
I eco Dan. When porting SISTR to plugin format it was not possible to generate custom report page as this module is only available for built-in workflows. Trying to use the same `AnalysisType` matching `SISTR_TYPING` caused name collision (the idea was to fool IRIDA to use plugin workflow instead of built-in on so final report page will be generated also in plugin).  

It would be nice to have this feature (custom html report generation/rendering) available for plugin workflow versions so it is possible to nicely render report pages using React or Javascript.
