### ISSUE TITLE
Job Error - Quast (5.0.2) 

### ISSUE THREAD

**Issue by glwinsor** [phac-nml/irida#678]
## Describe the bug
I'm running the annotation and assembly pipeline in irida-20.01.2/Galaxy 19.05 with Ubuntu 18.04 and am seeing an error at the quast step (just as it's starting).

```
/home/ubuntu/miniconda3/envs/__quast@5.0.2/bin/quast --threads 1 -o outputdir --min-contig 500 -l SRR3028776 --contig-thresholds 0,1000 /home/ubuntu/galaxy/database/files/000/dataset_233.dat

Version: 5.0.2

System information:
  OS: Linux-5.3.0-1017-aws-x86_64-with-debian-buster-sid (linux_64)
  Python version: 2.7.15
  CPUs number: 8

Started: 2020-05-04 18:15:44

Logging to /home/ubuntu/galaxy/database/jobs_directory/000/98/working/outputdir/quast.log

CWD: /home/ubuntu/galaxy/database/jobs_directory/000/98/working
Main parameters: 
  MODE: default, threads: 1, minimum contig length: 500, minimum alignment length: 65, \
  ambiguity: one, threshold for extensive misassembly size: 1000

WARNING: Can't draw plots: python-matplotlib is missing or corrupted.

Contigs:
  Pre-processing...

No module named joblib2
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/__quast@5.0.2/bin/quast", line 307, in <module>
    return_code = main(sys.argv[1:])
  File "/home/ubuntu/miniconda3/envs/__quast@5.0.2/bin/quast", line 107, in main
    contigs_fpaths, old_contigs_fpaths = qutils.correct_contigs(contigs_fpaths, corrected_dirpath, labels, reporting)
  File "/home/ubuntu/miniconda3/envs/__quast@5.0.2/opt/quast-5.0.2/quast_libs/qutils.py", line 180, in correct_contigs
    old_fpaths, corr_fpaths, broken_scaffold_fpaths, logs, is_fatal_error = run_parallel(parallel_correct_contigs, parallel_run_args, n_jobs)
  File "/home/ubuntu/miniconda3/envs/__quast@5.0.2/opt/quast-5.0.2/quast_libs/qutils.py", line 1062, in run_parallel
    from joblib2 import Parallel, delayed
ImportError: No module named joblib2
```

I've seen this error mentioned in the context of quast before:
https://github.com/ablab/quast/issues/108

So I activated the __ quast@5.0.2 environment and ran:
 `python -c 'import joblib'`

but there are no errors so it appears the package is there.

**Here are some other details about the workflow:**

![Screen Shot 2020-05-04 at 11 46 03 AM](https://user-images.githubusercontent.com/824607/81001621-df8c2480-8dfc-11ea-885d-367accfe255d.png)

**Galaxy Tool Parameters**

```

{
  "input_operon": "null",
  "input1": {
    "id": "9a558e080ece44e1",
    "uuid": "4981ceae-6f0b-4f68-a759-2b3ec90348c9"
  },
  "type_file": "contig",
  "annot": "null",
  "dbkey": "?",
  "large": "false",
  "threshold_contig": "0,1000",
  "__workflow_invocation_uuid__": "cb4e20fc8e2d11ea8f9802801bcabc93",
  "input": {
    "id": "9a558e080ece44e1",
    "uuid": "4981ceae-6f0b-4f68-a759-2b3ec90348c9"
  },
  "input_size": "",
  "input_ref": "null",
  "chromInfo": "/home/ubuntu/galaxy/tool-data/shared/ucsc/chrom/?.len",
  "min_contig": "500",
  "gene_selection": "prokaryotes"
}
```

Any idea how I could fix this?

Thanks.

**Comment by glwinsor** [comment]
I activated the  __quast@5.0.2 environment from the command from above:

`/home/ubuntu/miniconda3/envs/__quast@5.0.2/bin/quast --threads 1 -o outputdir --min-contig 500 -l SRR3028776 --contig-thresholds 0,1000 /home/ubuntu/galaxy/database/files/000/dataset_233.dat`

and it worked OK using python 3 (and joblib was installed under ./lib/python3.6/site-packages/) , however the error message above indicates it's running in a Python 2 environment.

**Comment by apetkau** [comment]
Hello @glwinsor, after you've activated `__quast@5.0.2` try running:

```
python --version
type python
conda list | grep python
```

To see what version of Python (and the full path to Python) you are using.

I wonder if it's possible that when you activate the environment yourself it's still using the system Python (and not one in conda), which is Python 3. But, when Galaxy runs the tool it's using the Python in the environment (or the system Python on some compute node) which is Python 2. And this is causing issues (since joblib2 I think is only for Python 2).

I'm not sure why this would happen though since conda should install the correct version of Python in the environment. But maybe it needs to be re-installed (e.g., `conda install python=3`)?

**Comment by apetkau** [comment]
Actually, I guess the output of the tool already shows it's running with Python 2, but we can still check if it's the system Python 2 (and so Python 3 may need to be re-installed in the quast environment).

**Comment by glwinsor** [comment]
Hi @apetkau here is the output of the three commands from within the __quast@5.0.2 which suggests to me that the environment is OK:

`python --version`
Python 3.6.10 :: Anaconda, Inc.

`type python`
python is hashed (/home/ubuntu/miniconda3/envs/__quast@5.0.2/bin/python)

`conda list | grep python`
python                    3.6.10               hcf32534_1  
python-dateutil           2.8.1                      py_0  

When I deactivate __quast@5.0.2, I go back to my system python is also python 3 but a different version:
Python 3.7.6
python is hashed (/home/ubuntu/miniconda3/bin/python)
python                    3.7.6                h0371630_2 

The job is running on the same machine because I currently have IRIDA and Galaxy on one AWS instance.  Going through this helps a lot ...  I see that the galaxy environment uses the same python as given in the above error message:

```
conda activate galaxy
python --version
```
Python 2.7.15

`type python`
python is hashed (/home/ubuntu/miniconda3/envs/galaxy/bin/python)

`conda list | grep python`
python                    2.7.15          h5a48372_1011_cpython    conda-forge
python_abi                2.7                    1_cp27mu    conda-forge

I'm not completely sure of how the environments are managed by galaxy. Is it possible that __quast@5.0.2 is being deactivated before the command above is called?

**Comment by glwinsor** [comment]
Sorry, accidentally closed the issue.

**Comment by ajkarloss** [comment]
I am also getting the same error now in irida-20.01.2/Galaxy 19.05 in CentOS 7. 
"ModuleNotFoundError: No module named 'joblib3'.

**Comment by glwinsor** [comment]
@apetkau that seems to have fixed it!  I did have a local_env.sh file set up to 1) add conda to the path and 2) source activate galaxy so I commented out the latter line.

Will this be a temporary fix to demonstrate cause or do you thing we can leave it for now?

**Comment by apetkau** [comment]
That's great. I wonder if the way Galaxy loads up environments for different dependencies has changed which is why I haven't seen it until now.

I do believe the file `local_env.sh` is loaded by the actual Galaxy web server/job schedulers. And there is another file `env.sh` that is loaded before executing each tool to include additional dependencies. But, the exact files that get loaded are all configured in your `galaxy.yml` file, so it depends on what it's been set to.

The reason I have instructions for creating a conda environment `galaxy` that gets loaded up in an environment file is because some tools were missing dependencies from the conda installs (or do not use conda at all), and so I needed a place to install additional dependencies. However, we've been updating some of the pipelines in IRIDA since some of that documentation was written, so it needs to be reviewed and updated at some point.

So, you can leave loading up at environment commented out, but I would test out all the pipelines again just to make sure they still work. I think it's really only the SNVPhyl pipeline that doesn't use conda for some of its tools that could be impacted. But I'm not sure.

**Comment by glwinsor** [comment]
Thanks @apetkau I'll do that for now and let you know how the other workflows turn out. My only worry would be that some of the plugins used by other groups may behave differently.

**Comment by glwinsor** [comment]
On first glance it looks like biohansel worked but RefSeq masher failed without any stderr or stdout file being made in the job directory (it previously worked before things were commented out).

**Comment by glwinsor** [comment]
SNVPhyl and SISTR workflows completed OK too.

**Comment by apetkau** [comment]
That's great to hear. I'm not sure why RefSeq Masher would fail, since all its dependencies should be contained in an isolated conda environment. But, at least the other tools are succeeding.

**Comment by glwinsor** [comment]
That was a strange case. I just re-ran RefSeq Masher and it turned out OK this time. Don't know why it failed the first time but I'll keep an eye on it.

**Comment by glwinsor** [comment]
Just wanted to post an update for anyone following this thread. I just upgraded to irida-20.05 and ran a workflow that uses the `__quast@5.0.2` environment and got an exception saying "ImportError: No module named joblib2" (opposite of the ImportError: No module named joblib3 I describe above).  No other changes had taken place to this environment.

I fixed it by going back to the config/local_env.sh and removing the comment. Workflow now works. Thus you need to comment out 'source activate galaxy' in this file if you are running 20.01.2 but that lines needs to be in place for 20.05.

**Comment by ajkarloss** [comment]
I dont see local_env.sh file inside galaxy/config. Should I create one? Also, the env.sh file.

**Comment by apetkau** [comment]
The `local_env.sh` is just used in case you wanted to load up additional environment settings before starting the Galaxy web server. By default you won't have one and have to create it. In the IRIDA docs I describe how you can use `local_env.sh` to load up Galaxy dependencies in a conda environment (in case they weren't available system-wide). If the Galaxy web server works fine for you then you probably don't need it.

For `env.sh`, this file is similar to `local_env.sh` but is used to define environment settings when running tools. You could look in here to see if you activate a conda environment which might be interfering with Python or library versions when running tools. I originally described using this file for tools where the conda environments were missing dependencies (or there was no conda environment at all). But Galaxy and Bioconda have advanced quite a bit since those were written so most tools don't need additional dependencies loaded by `env.sh`. So, you could try commenting out anything in this file in case you were using it.

**Comment by ajkarloss** [comment]
In my case: 

Found the FIX/culprit: QUAST was using python in ".venv" . NO idea why and how (still). I activated the python in the .venv and installed joblib and "matplotlib"


May be if someone knows why or how QUAST could have been pointed to use python in .venv instead of conda

**Comment by mrmrwinter** [comment]
Hi, Im having this issue but when running standalone QUAST.

I receive the joblib3 error, but this is the results of a traced back error where it cannot find joblib, goes to an exception to look for joblib2 and 3 in python 2, then throws the error.

`Traceback (most recent call last):`
`File "/home/531734/.conda/envs/quast/bin/quast", line 307, in <module>`
`    return_code = main(sys.argv[1:])`
`File "/home/531734/.conda/envs/quast/bin/quast", line 107, in main`
`    contigs_fpaths, old_contigs_fpaths = qutils.correct_contigs(contigs_fpaths, corrected_dirpath, labels, reporting)`
`  File "/home/531734/.conda/envs/quast/opt/quast-5.0.2/quast_libs/qutils.py", line 180, in correct_contigs`
`    old_fpaths, corr_fpaths, broken_scaffold_fpaths, logs, is_fatal_error = run_parallel(parallel_correct_contigs, parallel_run_args, n_jobs)`
`  File "/home/531734/.conda/envs/quast/opt/quast-5.0.2/quast_libs/qutils.py", line 1064, in run_parallel`
`    from joblib3 import Parallel, delayed`
`ModuleNotFoundError: No module named 'joblib3'``

Strangely, when i run quast in my environment locally it works, when i run it as a batch job, calling the same environment, it hits the error.
