### ISSUE TITLE
Missing button for filtering results in analysis output downloads

### ISSUE THREAD

**Issue by apetkau** [phac-nml/irida#899]
## Describe the bug

In IRIDA version `19.05.1` there existed a button you could use to filter the analysis output files displayed in a table:

![image](https://user-images.githubusercontent.com/200517/103101546-c3cccd00-45dd-11eb-9aa6-8f1959ab2e72.png)

However, in IRIDA `20.09.4` this button no longer exists:

![image](https://user-images.githubusercontent.com/200517/103101562-d2b37f80-45dd-11eb-917f-cb5b3c98334c.png)

## Steps to reproduce the problem

1. In an older version of IRIDA (`19.05.1`) go to a particular project.
2. Within the project go to **Analyses > Shared Single Sample Analysis Outputs**
3. Hover over the table column headers (**File** or **Analysis Type**) and you should be given the option to filter the table.
4. Repeat steps 1-3 in a newer IRIDA (`20.09.4`) and the option to filter the table is missing.

## Expected behaviour
I expected to be able to filter the table of analysis results based on user-entered strings.

## Additional context
None.

**Comment by dorbarker** [comment]
This completely prevented my work from happening today. 

Here's the scenario:
I needed to get 267 assemblies out of IRIDA. The 267 samples are a subset of a project containing 4,234 samples total. Because IRIDA has never been able to filter Analysis results by sample name (see #778) and with the other filtering now broken, I'm left with two options:

1. Scroll through the 80,446 (4,234 samples with 19 files generated per _Assembly and Annotation_ run) files to manually click on the 267 files I actually want
2. Download the entire ~25 GB  zip archive and extract the files I want from that, and discard the rest

These are unappealing options. Further, should I attempt to go with Option 2, the UI indicates that 38,000 files will be downloaded, so I can't even be sure that all 80,446 files are truly downloading or not.
